export const AUTH_USER = 'AUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';
export const CHANGE_USER_PICTURE = 'CHANGE_USER_PICTURE';
export const FETCH_WORKOUTS = 'FETCH_WORKOUTS';
export const SELECT_WORKOUT = 'SELECT_WORKOUT';
export const TRAINER_CLIENT_LIST = 'TRAINER_CLIENT_LIST';
